- hosts: localhost
  tasks:
  - name: install desktop apps from apt
    become: yes
    ansible.builtin.apt:
      update_cache: yes
      pkg:
        - vlc
        - audacity
        - virt-manager
        - thunderbird
        - chromium
        - dropbox
        - nemo-dropbox
        - ssh-askpass
        - tmux

  - name: install flatpak pakcages from flathub
    community.general.flatpak:
      name:
        - com.bitwarden.desktop
        - com.discordapp.Discord
        - com.visualstudio.code

  - name: install alacritty terminal via cargo
    community.general.cargo:
      name: alacritty
      executable: "$HOME/.cargo/bin/cargo"

  - name: Add alacritty shortcut system menu
    copy:
      dest: "{{ ansible_env.HOME }}/.local/share/applications/alacritty.desktop"
      content: |
        [Desktop Entry]
        Version=1.0
        Type=Application
        Name=Alacritty
        Comment=Alacritty - A fat, cross-platform, OpenGL terminal emulator.
        Exec=/home/shichijo/.cargo/bin/alacritty
        Terminal=false
        Icon=utilities-terminal
        Categories=System;