- hosts: localhost
  tasks:
    - name: Add docker repo key
      become: yes
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        #keyring: /etc/apt/keyring/docker.gpg

    - name: Add docker official repo
      become: yes
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"

    - name: Install Docker Desktop
      become: yes
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - docker-ce
    
    - name: Print required command
      debug: msg="Please run $ sudo usermod -aG docker $(whoami)"